steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=$_API_URL'
      - '-t'
      - 'gcr.io/$PROJECT_ID/voyager-web:latest'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/voyager-web:latest'
substitutions:
  _API_URL: 'http://localhost:8000'
options:
  logging: CLOUD_LOGGING_ONLY
