"""cria tabelas de execucao, roteiro e uso

Revision ID: 3692c0743c61
Revises:
Create Date: 2026-07-30 10:34:20.975470
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "3692c0743c61"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Aplica a migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "executions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "CANCELLED",
                name="execution_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("origem", sa.String(length=200), nullable=False),
        sa.Column("destino", sa.String(length=200), nullable=False),
        sa.Column("dias", sa.Integer(), nullable=False),
        sa.Column("interesses", sa.String(length=500), nullable=False),
        sa.Column("moeda", sa.String(length=3), nullable=False),
        sa.Column("idioma", sa.String(length=10), nullable=False),
        sa.Column("briefing_hash", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("llm_gateway", sa.String(length=50), nullable=True),
        sa.Column("used_fallback", sa.Boolean(), nullable=False),
        sa.Column("served_from_cache", sa.Boolean(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("client_ip_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_executions_briefing_hash"),
        "executions",
        ["briefing_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_executions_created_at"), "executions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_executions_status"), "executions", ["status"], unique=False
    )
    op.create_index(
        "ix_executions_status_created",
        "executions",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "itineraries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=False),
        sa.Column("content_markdown", sa.Text(), nullable=False),
        sa.Column(
            "locations_geojson", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"], ["executions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_itineraries_execution_id"),
        "itineraries",
        ["execution_id"],
        unique=False,
    )
    op.create_table(
        "usage_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("gateway", sa.String(length=50), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("baseline_cost_usd", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"], ["executions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_usage_records_created_at"),
        "usage_records",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_usage_records_execution_id"),
        "usage_records",
        ["execution_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverte a migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usage_records_execution_id"), table_name="usage_records")
    op.drop_index(op.f("ix_usage_records_created_at"), table_name="usage_records")
    op.drop_table("usage_records")
    op.drop_index(op.f("ix_itineraries_execution_id"), table_name="itineraries")
    op.drop_table("itineraries")
    op.drop_index("ix_executions_status_created", table_name="executions")
    op.drop_index(op.f("ix_executions_status"), table_name="executions")
    op.drop_index(op.f("ix_executions_created_at"), table_name="executions")
    op.drop_index(op.f("ix_executions_briefing_hash"), table_name="executions")
    op.drop_table("executions")
    # ### end Alembic commands ###
